"""Initial migration

Revision ID: e192765b89bd
Revises: 
Create Date: 2025-04-13 19:31:02.649234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e192765b89bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_questions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_testID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tests', ['testID'], ['test_id'])

    with op.batch_alter_table('student_tests', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('student_tests_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('student_tests_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['account_id'])
        batch_op.create_foreign_key(None, 'tests', ['test_id'], ['test_id'])
        batch_op.drop_column('grade')
        batch_op.drop_column('id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('test_taken')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint('tests_ibfk_1', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tests_ibfk_1', 'students', ['student_id'], ['account_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_taken', mysql.DOUBLE(asdecimal=True), nullable=True))

    with op.batch_alter_table('student_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('grade', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_tests_ibfk_1', 'students', ['student_id'], ['account_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('student_tests_ibfk_2', 'tests', ['test_id'], ['test_id'], ondelete='CASCADE')
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_testID', 'tests', ['testID'], ['test_id'], ondelete='CASCADE')

    op.create_table('test_questions',
    sa.Column('test_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name='test_questions_ibfk_2'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], name='test_questions_ibfk_1'),
    sa.PrimaryKeyConstraint('test_id', 'question_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
